# Generated by Django 3.0.1 on 2021-09-18 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app124', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='profile_image',
            field=models.ImageField(upload_to='myphoto'),
        ),
    ]
