# Generated by Django 3.0.1 on 2021-09-18 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app124', '0003_auto_20210918_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to='my_image/'),
        ),
    ]
