# Generated by Django 3.0.1 on 2021-09-18 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app124', '0004_auto_20210918_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='my_image/'),
        ),
    ]
